(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['footer'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"container-fluid\" style=\"color: #FFF; background-color: #000; padding: 40px 40px 40px 40px; justify-content: center\">\n\n  <div class=\"row\">\n    <div class=\"col-sm-6 bottom-col\">\n      <div>\n        <img src=\"static/binancex-logo.svg\" style=\"width: 120px; margin: 0px 0px 15px -5px; text-align: left; justify-content: left\"></img>\n      </div>\n      <div style=\"\">\n        Stay informed.<p><i>Join the X Developers Network (XDN)</i>\n      </div>\n      <div style=\"\">\n        <a class=\"btn-sm btn-primary binance-button\" href=\"https://bit.ly/x-devs\" target=\"_new\" role=\"button\">Sign up for XDN</a>\n      </div>\n\n    </div>\n\n    <div class=\"col-sm-3 bottom-col\">\n      <div class=\"bottom-right-menu\">\n        Menu\n      </div>\n      <div class=\"bottom-menu\">\n        <div class=\"bottom-menu-item\">\n          <a href=\"\">Home</a>\n        </div>\n        <div class=\"bottom-menu-item\">\n          <a href=\"\">Learn</a>\n        </div>\n        <div class=\"bottom-menu-item\">\n          <a href=\"\">Collaborate</a>\n        </div>\n        <div class=\"bottom-menu-item\">\n          <a href=\"\">Grow</a>\n        </div>\n      </div>\n    </div>\n\n    <div class=\"col-sm-3 bottom-col\">\n      <div class=\"bottom-right-menu\">\n        Community\n      </div>\n      <div class=\"bottom-menu\">\n        <div class=\"bottom-menu-item\">\n          <a  href=\"https://twitter.com/binancex\" target=\"_new\"><i class=\"fab fa-twitter\" style=\"margin-right: 5px;\"></i>Twitter</a>\n        </div>\n        <div class=\"bottom-menu-item\">\n          <a  href=\"https://github.com/binancex\" target=\"_new\"><i class=\"fab fa-github\" style=\"margin-right: 5px;\"></i>GitHub</a>\n        </div>\n      </div>\n    </div>\n\n  </div>\n\n\n</div>\n\n<div style=\"text-align: center; background-color: #000; font-size: 12px; padding: 40px 0; color: #666\">\n    &copy; 2019 Binance.com All rights reserved\n</div>";
},"useData":true});
templates['nav'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: #202020\">\n  <a class=\"navbar-brand\" href=\"#\">\n    <img src=\"static/binancex-logo.svg\" style=\"width: 160px\"></img>\n  </a>\n  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n    <span class=\"navbar-toggler-icon\"></span>\n  </button>\n  <div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarNav\">\n    <ul class=\"navbar-nav\">\n      <li class=\"nav-item "
    + alias4(((helper = (helper = helpers.home_status || (depth0 != null ? depth0.home_status : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"home_status","hash":{},"data":data}) : helper)))
    + "\">\n        <a class=\"nav-link\" href=\"./index.html\"><i class=\"fas fa-home\"></i> <span class=\"sr-only\">(current)</span></a>\n      </li>\n      <li class=\"nav-item "
    + alias4(((helper = (helper = helpers.learn_status || (depth0 != null ? depth0.learn_status : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"learn_status","hash":{},"data":data}) : helper)))
    + "\">\n        <a class=\"nav-link\" href=\"./learn.html\">Learn</a>\n      </li>\n      <li class=\"nav-item "
    + alias4(((helper = (helper = helpers.collaborate_status || (depth0 != null ? depth0.collaborate_status : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"collaborate_status","hash":{},"data":data}) : helper)))
    + "\">\n        <a class=\"nav-link\" href=\"./collaborate.html\">Collaborate</a>\n      </li>\n      <li class=\"nav-item "
    + alias4(((helper = (helper = helpers.grow_status || (depth0 != null ? depth0.grow_status : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"grow_status","hash":{},"data":data}) : helper)))
    + "\">\n        <a class=\"nav-link\" href=\"./grow.html\">Grow</a>\n      </li>\n      <li class=\"nav-item\">\n        <a class=\"nav-link\" href=\"https://twitter.com/binancex\" target=\"_new\"><i class=\"fab fa-twitter\"></i></a>\n      </li>\n      <li class=\"nav-item\">\n        <a class=\"nav-link\" href=\"https://github.com/binancex\" target=\"_new\"><i class=\"fab fa-github\"></i></a>\n      </li>\n\n    </ul>\n  </div>\n</nav>";
},"useData":true});
})();